// Player has to guess a random number generated by the computer, within a chosen range of difficulty

#include <time.h>
#include <stdlib.h>
#include <stdio.h>

int main()
{
    int i, gs,rm;
    srand(time(NULL));
    printf("\n\nWELCOME TO GUESS THE NUMBER, computer chooses a number between 1-10, you have to guess it within 3 turns:\n"); 

    rm = rand() % 10 + 1;
    for (i = 1; i <= 3; i++)
    {
        printf("\n(Total No Of Turns Remaining = %d), GUESS THE NUMBER: ", (3 - i + 1));
        scanf("%d", &gs);
        if (gs == rm)
            goto result;
        if (i == 3)
        {
            printf("\nSORRY!!! BUT ALL YOUR TURNS ARE OVER\nThe Number Was:%d\nBetter Luck Next Time...\n\n", rm);
            exit(0);
        }
        else if (gs > rm)
            printf("%d is greater than the number", gs);
        else if (gs < rm)
            printf("%d is smaller than the number", gs);
    }
result:
    printf("\nYAY!!!\nYOU WON...\n\n");
    return 0;
}
