// Player has to guess a random number generated by the computer, within a chosen range of difficulty

#include <time.h>
#include <stdlib.h>
#include <stdio.h>

int main()
{
    int i, gs, ch, turn, rm, x;
    srand(time(NULL));
    printf("\n\nWELCOME TO GUESS THE NUMBER, computer chooses a number and you have to guess it...\nSelect the difficulty level:-\nEASY(1-10),      ENTER 1:\nMEDIUM(1-10),    ENTER 2:\nDIFFICULT(1-20), ENTER 3:\nEXTREME(1-200),  ENTER 4:\n\n=> ");
    scanf("%d", &ch);
    if (ch == 1)
    {
        x = 10;
        turn = 3;
    }
    else if (ch == 2)
    {
        x = 10;
        turn = 2;
    }
    else if (ch == 3)
    {
        x = 20;
        turn = 3;
    }
    else if (ch == 4)
    {
        x = 200;
        turn = 7;
    }
    else
    {
        printf("INVALID INPUT");
        exit(0);
    }
    rm = rand() % x + 1;
    printf("\n");
    for (i = 1; i <= turn; i++)
    {
        printf("\n(Total No Of Turns Remaining = %d), GUESS THE NUMBER: ", turn - i + 1);
        scanf("%d", &gs);
        if (gs == rm)
            goto result;
        if (i == turn)
        {
            printf("\nSORRY!!! BUT ALL YOUR TURNS ARE OVER\nThe Number Was:%d\nBetter Luck Next Time...\n\n", rm);
            exit(0);
        }
        else if (gs > rm)
            printf("%d is greater than the number", gs);
        else if (gs < rm)
            printf("%d is smaller than the number", gs);
    }
result:
    printf("\nYAY!!!\nYOU WON...\n\n");
    return 0;
}
